const sampleData = [
  {
    _id: '5f6ebd0914590aafbcc98430',
    pid: 1,
    name: 'Generic Frozen Chair',
    rating: 2.52,
    reviews_count: 2933,
    price: '$26.00',
    image_url: 'https://fec-lego-recommendation.s3-us-west-1.amazonaws.com/5.jpeg',
    label: 0,
    show_most_like: 'Practical',
    wishlist: false,
    in_cart: false,
    __v: 0,
  },
  {
    _id: '5f6ebd0914590aafbcc9842f',
    pid: 2,
    name: 'Tasty Steel Car',
    rating: 3.99,
    reviews_count: 2815,
    price: '$87.00',
    image_url: 'https://fec-lego-recommendation.s3-us-west-1.amazonaws.com/6.jpeg',
    label: 1,
    show_most_like: 'Handmade',
    wishlist: false,
    in_cart: false,
    __v: 0,
  },
  {
    _id: '5f6ebd0914590aafbcc9842d',
    pid: 3,
    name: 'Ergonomic Frozen Chips',
    rating: 1.17,
    reviews_count: 205,
    price: '$53.00',
    image_url: 'https://fec-lego-recommendation.s3-us-west-1.amazonaws.com/4.jpeg',
    label: 2,
    show_most_like: 'Generic',
    wishlist: false,
    in_cart: false,
    __v: 0,
  },
  {
    _id: '5f6ebd0914590aafbcc98421',
    pid: 4,
    name: 'Fantastic Wooden Pants',
    rating: 1.67,
    reviews_count: 727,
    price: '$57.00',
    image_url: 'https://fec-lego-recommendation.s3-us-west-1.amazonaws.com/1.jpeg',
    label: 0,
    show_most_like: 'Refined',
    wishlist: false,
    in_cart: false,
    __v: 0,
  },
  {
    _id: '5f6ebd0914590aafbcc98420',
    pid: 5,
    name: 'Handcrafted Cotton Fish',
    rating: 0.3,
    reviews_count: 1455,
    price: '$88.00',
    image_url: 'https://fec-lego-recommendation.s3-us-west-1.amazonaws.com/9.jpeg',
    label: 3,
    show_most_like: 'Intelligent',
    wishlist: false,
    in_cart: false,
    __v: 0,
  },
  {
    _id: '5f6ebd0914590aafbcc9841f',
    pid: 6,
    name: 'Gorgeous Wooden Bacon',
    rating: 0.98,
    reviews_count: 2085,
    price: '$90.00',
    image_url: 'https://fec-lego-recommendation.s3-us-west-1.amazonaws.com/1.jpeg',
    label: 0,
    show_most_like: 'Handmade',
    wishlist: false,
    in_cart: false,
    __v: 0,
  },
  {
    _id: '5f6ebd0914590aafbcc9842f',
    pid: 7,
    name: 'Tasty Steel Car',
    rating: 3.99,
    reviews_count: 2815,
    price: '$87.00',
    image_url: 'https://fec-lego-recommendation.s3-us-west-1.amazonaws.com/6.jpeg',
    label: 1,
    show_most_like: 'Handmade',
    wishlist: false,
    in_cart: false,
    __v: 0,
  },
  {
    _id: '5f6ebd0914590aafbcc9842d',
    pid: 8,
    name: 'Ergonomic Frozen Chips',
    rating: 1.17,
    reviews_count: 205,
    price: '$53.00',
    image_url: 'https://fec-lego-recommendation.s3-us-west-1.amazonaws.com/4.jpeg',
    label: 2,
    show_most_like: 'Generic',
    wishlist: false,
    in_cart: false,
    __v: 0,
  },
];

export default sampleData;
